name: Promote Snap to Stable

on:
  release:
    types: [published]

jobs:
  promote:
    name: Promote Snap
    runs-on: ubuntu-latest
    steps:
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Promote Snap to Stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SNAPCRAFT_HAS_TTY: "true"
        run: |
          echo "y" | snapcraft promote pocket-planner --from-channel edge --to-channel stable
